export type Trait =
  | 'AAAUUUGH!!!'
  | 'Adaptable'
  | 'Aerial Bombardment'
  | 'Amphibious'
  | 'Arcadian'
  | 'Archers'
  | 'Armor Osmosis'
  | 'Armored Carapace'
  | 'Barbs'
  | 'Battle Hymn'
  | 'Beacon of Courage'
  | 'Beacon of Order'
  | 'Better than One'
  | 'Big'
  | 'Blanket Fire'
  | 'Bless the Rains'
  | 'Blinding'
  | 'Burning'
  | 'Burrow'
  | 'Chaos Vulnerability'
  | 'Charge'
  | 'Chorus of Victory'
  | 'Close Enough'
  | 'Close Range'
  | 'Cloud of Darkness'
  | 'Collateral Damage'
  | 'Consume'
  | 'Corrode'
  | 'Corrosive Breath'
  | 'Create Dead'
  | 'Cunning Ambush'
  | 'Damage Resistant'
  | 'Daylight Weakness'
  | 'Dead'
  | 'Defy Gravity'
  | 'Dig!'
  | 'Dire Hyena Mounts'
  | 'Directed Fire'
  | 'Disruptive'
  | 'Draconic Ancestry'
  | 'Dragonkin'
  | 'Drone'
  | 'Elf-shot'
  | 'Embiggen'
  | 'Eternal'
  | 'Ethereal'
  | 'Expert Fade'
  | 'Fade'
  | 'Fast Siege Weapon'
  | 'Fast Siege Weapon (Heavy)'
  | 'Fearless'
  | 'Fearsome'
  | 'Feast'
  | 'Find Path'
  | 'Fire Blast'
  | 'Fire Breath'
  | 'Fire Immunity'
  | 'Flaming Weapons'
  | 'First Strike'
  | '“Follow the Standard!”'
  | 'Frame'
  | 'Fury'
  | 'Goblin Battle Platform'
  | 'Guerrillas'
  | 'Gulp'
  | 'Harpoon'
  | 'Harrowing'
  | 'Hellfire Cannons'
  | 'It Will Burn As We Burn'
  | 'Jaunt'
  | 'Lightning'
  | 'Made from Magic'
  | 'Maneuver: Break Them'
  | 'Maneuver: Focused Aim'
  | 'Maneuver: Scamp-ede of Corgis'
  | 'Mass Protection Against Evil'
  | 'Master Elf-shot'
  | 'Max Burn!'
  | 'Meld'
  | 'Mobile'
  | 'Mobile Battery'
  | 'Nature’s Bond'
  | 'None'
  | 'Now This Is an AAAUUUGH!!!'
  | 'Noxious Fog'
  | 'Offensive'
  | 'Only the Smart Survive'
  | 'Owlbears Can’t Fly?!'
  | 'Pack Tactics'
  | 'Pike Training'
  | 'Plagued'
  | 'Point Blank'
  | 'Poisonous'
  | "Pool of Soul’s Blood"
  | 'Quadruped'
  | 'Ram Riders'
  | 'Reckless'
  | 'Reflector'
  | 'Regenerate'
  | 'Relentless'
  | 'Resolute'
  | 'Rime'
  | 'Rock!'
  | 'Rockbreaker'
  | 'Rolling Thunder'
  | 'Rush'
  | 'Savage'
  | 'Scourge of the Wild'
  | 'Scouts'
  | 'Screech'
  | 'Shock Troops'
  | 'Siege Engine'
  | 'Smoke Screen'
  | 'Spit Upon Their Horns'
  | 'Stalwart'
  | 'Stinky'
  | 'Stone'
  | 'Stoneskin'
  | 'Strength in Numbers'
  | 'Stupid'
  | 'Swords of the Dragon Lord'
  | 'To the Death'
  | 'Veterans of a Thousand Wars'
  | 'Wail'
  | 'Warbred'
  | 'Wave'
  | 'Whirlwind'
  | 'You Follow!'
  | 'Amphibious'
  | 'Bred for war'
  | 'Brutal'
  | 'Courageous'
  | 'Eternal'
  | 'Frenzy'
  | 'Horrify'
  | 'Martial'
  | 'Mindless'
  | 'Regenerate'
  | 'Ravenous'
  | 'Rock-hurler'
  | 'Savage'
  | 'Stalwart'
  | 'Twisting Roots'
  | 'Undead'
  | 'Charge'
  | 'Always Diminished'
  | 'Siege Engine';